src/main/java/pl/modzelewski/damian/animalsjsf/model/Animal.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.modzelewski.damian.animalsjsf.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author Damian
 */
public class Animal implements Serializable{
    private int id;
    private String name;
    private String species;
    private double weight;
    private BigDecimal price;
    private String imgPath = "img/default.jpg";
    private String description = "No description has been added";

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSpecies() {
        return species;
    }

    public void setSpecies(String species) {
        this.species = species;
    }

    public double getWeight() {
        return weight;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }

    public BigDecimal getPrice() {
        price = price.setScale(2, RoundingMode.CEILING);
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public String getImgPath() {
        return imgPath;
    }

    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    public Animal(int id, String name, String species, double weight, BigDecimal price) {
        this.id = id;
        this.name = name;
        this.species = species;
        this.weight = weight;
        this.price = price;
    }

    public Animal(int id, String name, String species, double weight, BigDecimal price, String imgPath) {
        this.id = id;
        this.name = name;
        this.species = species;
        this.weight = weight;
        this.price = price;
        this.imgPath = imgPath;
    }

    public Animal() {
    }
    
    
    
    
}

src/main/java/pl/modzelewski/damian/animalsjsf/model/Gender.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.modzelewski.damian.animalsjsf.model;

/**
 *
 * @author Damian
 */
public enum Gender {
    MALE,
        FEMALE,
        BIGENDER,
        ANDROGYNE,
        NEUTRORIS,
        INTERGENDER,
        DEMIBOY,
        DEMIGIRL,
        GENDERQUEEN,
        POLIGENDER,
        EPICENE,
        GENDERFLUID,
        TRANSGENDER,
        AGENDER,
        TRANSVESTI,
        BUTCH,
        ALIAGENDER,
        AESTHETIGENDER,
        AMBIGENDER,
        ANGENIAL,
        ASTRALGENDER,
        ASTERGENDER,
        AUTOGENDER,
        BIOGENDER,
        CASSGENDER,
        CISGENDER,
        CLOUDGENDER,
        COLORGENDER,
        DEMIFLUX,
        DELICIAGENDER,
        EXGENDER,
        GENDERBLANK,
        GLASSGENDER,
        GENDERPUNK,
        HELIOGENDER,
        JUXERA,
        IMPERIGENDER,
        HYDROGENDER,
        SUBGENDER,
        VELOCIGENDER
}

src/main/java/pl/modzelewski/damian/animalsjsf/model/User.java
package pl.modzelewski.damian.animalsjsf.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;

/**
 *
 * @author Damian
 */
public class User implements Serializable{
    
    private String login;
    private String password;
    private String name;
    private Gender gender;
    private List<Animal> ownedAnimals;
    private BigDecimal money;

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public List<Animal> getOwnedAnimals() {
        return ownedAnimals;
    }

    public void setOwnedAnimals(List<Animal> ownedAnimals) {
        this.ownedAnimals = ownedAnimals;
    }

    public BigDecimal getMoney() {
        money = money.setScale(2, RoundingMode.CEILING);
        return money;
    }

    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    public User() {
    }

    public User(BigDecimal money) {
        this.money = money;
    }
    
    
    
}

src/main/java/pl/modzelewski/damian/animalsjsf/views/AddAnimalBean.java
package pl.modzelewski.damian.animalsjsf.views;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.File;
import java.io.InputStream;
import java.io.Serializable;
import java.math.BigDecimal;
import javax.faces.bean.ManagedBean;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.Part;
import org.apache.commons.io.IOUtils;
import pl.modzelewski.damian.animalsjsf.databases.AnimalDatabase;
import pl.modzelewski.damian.animalsjsf.model.*;

/**
 *
 * @author Damian
 */
@ManagedBean
@Named
@ViewScoped
public class AddAnimalBean implements Serializable {

    @Inject
    private AnimalDatabase animalStore;

    private String name;
    private String species;
    private double weight;
    private BigDecimal price;
    private String imgPath;
    private String description;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSpecies() {
        return species;
    }

    public void setSpecies(String species) {
        this.species = species;
    }

    public double getWeight() {
        return weight;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public String getImgPath() {
        return imgPath;
    }

    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void addAnimal() {
        Animal newAnimal = new Animal();
        newAnimal.setName(name);
        newAnimal.setSpecies(species);
        newAnimal.setWeight(weight);
        newAnimal.setPrice(price);
        newAnimal.setDescription(description);
        newAnimal.setId(animalStore.getAnimals().size() + 1);
        animalStore.getAnimals().add(newAnimal);
    }

}

src/main/java/pl/modzelewski/damian/animalsjsf/views/AnimalListBean.java
package pl.modzelewski.damian.animalsjsf.views;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import pl.modzelewski.damian.animalsjsf.databases.*;
import pl.modzelewski.damian.animalsjsf.model.*;

/**
 *
 * @author Damian
 */
@ManagedBean
@ViewScoped
public class AnimalListBean implements Serializable {

    @Inject
    private AnimalDatabase animalStore;

    @Inject
    private UserDatabase userStore;

    private List<Animal> animals;
    private User user;

    public List<Animal> getAnimals() {
        animals = null;
        if (animals == null) {
            animals = animalStore.getAnimals();
        }
        return animals;
    }

    public User getUser() {
        if (user == null) {
            user = userStore.getUser();
        }
        return user;
    }

    public void buy(Animal animal) {
        BigDecimal userMoney = userStore.getUser().getMoney();
        BigDecimal animalPrice = animal.getPrice();
        userStore.getUser().setMoney(userMoney.subtract(animalPrice));
        userStore.getUser().getOwnedAnimals().add(animal);
    }

    public boolean isEnoughMoney(Animal animal) {
        BigDecimal userMoney = userStore.getUser().getMoney();
        BigDecimal animalPrice = animal.getPrice();
        int res = userMoney.compareTo(animalPrice);
        if (res >= 1) {
            return true;
        } else {
            return false;
        }
    }

}

src/main/java/pl/modzelewski/damian/animalsjsf/views/AnimalViewBean.java
package pl.modzelewski.damian.animalsjsf.views;

import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import pl.modzelewski.damian.animalsjsf.databases.AnimalDatabase;
import pl.modzelewski.damian.animalsjsf.model.*;

/**
 *
 * @author Damian
 */
@ManagedBean
@Named
@ViewScoped
public class AnimalViewBean implements Serializable{

    @Inject
    private AnimalDatabase animalStore;
    
    private int animalId;
    private Animal animal;

    public int getAnimalId() {
        return animalId;
    }

    public void setAnimalId(int animalId) {
        this.animalId = animalId;
    }

    public Animal getAnimal() {
        if(animal==null){
            animal = animalStore.getAnimal(animalId-1);
        }
        return animal;
    } 
    
}

src/main/java/pl/modzelewski/damian/animalsjsf/views/ChatBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.modzelewski.damian.animalsjsf.views;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.inject.Inject;
import pl.modzelewski.damian.animalsjsf.databases.UserDatabase;

/**
 *
 * @author Damian
 */
@ManagedBean
@ApplicationScoped
public class ChatBean {
    
    @Inject
    UserDatabase user;
    
    private List<String> chatLog = new ArrayList<>();
    private String chat;
    private String msg;

    public List<String> getChatLog() {
        return chatLog;
    }

    public String getChat() {
        chat = chatLog.stream().collect(Collectors.joining());
        return chat;
    }

    public void setChat(String chat) {
        this.chat = chat;
    }
    
    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }
    
    public void send(){
        if(msg!=null){
            chatLog.add(user.getUser().getLogin()+": "+msg+"\n");
            msg=null;
        }
    }
    
}

src/main/java/pl/modzelewski/damian/animalsjsf/views/UserProfileBean.java
package pl.modzelewski.damian.animalsjsf.views;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import pl.modzelewski.damian.animalsjsf.databases.UserDatabase;
import pl.modzelewski.damian.animalsjsf.model.*;

/**
 *
 * @author Damian
 */
@Named
@ViewScoped
public class UserProfileBean implements Serializable {

    @Inject
    private UserDatabase userDB;

    private User user;
    private String newName;
    private Gender[] genders = Gender.values();
    private boolean showInput = false;
    private boolean showGenders = false;

    public User getUser() {
        if (user == null) {
            user = userDB.getUser();
        }
        return user;
    }
    
    public String getNewName() {
        return newName;
    }

    public void setNewName(String newName) {
        this.newName = newName;
    }

    public Gender[] getGenders() {
        return genders;
    }

    public void setGenders(Gender[] genders) {
        this.genders = genders;
    }
    
    public boolean isShowGenders() {
        return showGenders;
    }

    public void setShowGenders(boolean showGenders) {
        this.showGenders = showGenders;
    }

    public boolean isShowInput() {
        return showInput;
    }

    public void setShowInput(boolean showInput) {
        this.showInput = showInput;
    }

    public boolean isListPopulated() {
        return !user.getOwnedAnimals().isEmpty();
    }

    public void changeName(){
        user.setName(newName);
        newName=null;
    }
}

src/main/webapp/add_animal.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    template="/template.xhtml">
    <ui:define name="title">
        <title>Add animal</title>
    </ui:define>
    <ui:define name="content">
        <f:view>
            <h:form  enctype="multipart/form-data">
                <h:panelGrid columns="2">
                    <h:outputLabel value="Name" for="name"/>
                    <h:inputText id="name" value="#{addAnimalBean.name}"/>

                    <h:outputLabel value="Species" for="species"/>
                    <h:inputText id="species" value="#{addAnimalBean.species}"/>

                    <h:outputLabel value="Weight" for="weight"/>
                    <h:inputText id="weight" value="#{addAnimalBean.weight}"/>

                    <h:outputLabel value="Price" for="price"/>
                    <h:inputText id="price" value="#{addAnimalBean.price}"/>

                    <h:outputLabel value="Description" for="description"/>
                    <h:inputTextarea id="description" value="#{addAnimalBean.description}"/>

                    <h:outputLabel value="Picture(JPA required)" for="picture"/>
                    <h:inputFile id="picture"/>

                    <h:commandButton value="Save" action="#{addAnimalBean.addAnimal()}"/>
                </h:panelGrid>
            </h:form>
        </f:view>
    </ui:define>
</ui:composition>

src/main/webapp/animal_list.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    template="/template.xhtml">
    <ui:define name="title">
        <title>Main page</title>
    </ui:define>
    <ui:define name="content">
        <f:view>
            <h:dataTable id="listTable" var="animal" value="#{animalListBean.animals}" columnClasses="img, tableName, tableSpecies, price, tableInput, tableInput">

                <h:column>
                    <h:graphicImage library="default" name="#{animal.imgPath}" alt="#{animal.name}+.img"/>
                </h:column>
                <h:column class="tableName">
                    #{animal.name}
                </h:column>
                <h:column>
                    #{animal.species}                    
                </h:column>
                <h:column>
                    #{animal.price}$     
                </h:column>
                <h:column>
                    <h:button outcome="animal_view" value="Description">
                        <f:param name="animalId" value="#{animal.id}"/>
                    </h:button>
                </h:column>
                <h:column>
                    <h:form>
                        <h:commandButton value="BUY" action="#{animalListBean.buy(animal)}" disabled="#{!testView.isEnoughMoney(animal)}"/>
                    </h:form>
                </h:column>
            </h:dataTable>
        </f:view>
    </ui:define>
</ui:composition>

src/main/webapp/animal_view.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    template="/template.xhtml">
    <f:metadata>
        <f:viewParam name="animalId" value="#{animalViewBean.animalId}"/>
    </f:metadata>
    <ui:define name="title">
        <title>Main page</title>
    </ui:define>
    <ui:define name="content">
        <f:view>
            <h:panelGrid columns="2" class="descriptionTable">
                <h:graphicImage library="default" name="#{animalViewBean.animal.imgPath}"/>
                <h:panelGrid columns="4" class="descriptionData" >
                    <h:outputLabel value="Name" class="descriptionTH"/>
                    <h:outputLabel value="Species" class="descriptionTH"/>
                    <h:outputLabel value="Weight" class="descriptionTH"/>
                    <h:outputLabel value="Price" class="descriptionTH"/>
                    <h:outputText value="#{animalViewBean.animal.name}"/>
                    <h:outputText value="#{animalViewBean.animal.species}"/>
                    <h:outputText value="#{animalViewBean.animal.weight}kg"/>
                    <h:outputText value="#{animalViewBean.animal.price}$"/>
                </h:panelGrid>
                <h:outputLabel value="Description" class="descriptionTH"/>
                <h:outputText value="#{animalViewBean.animal.description}"/>
            </h:panelGrid>
        </f:view>
    </ui:define>
</ui:composition>

src/main/webapp/chat.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    template="/template.xhtml">
    <ui:define name="title">
        <title>Chat</title>
    </ui:define>
    <ui:define name="content">
        <h:form>
            <div class="chat">
                <h:inputTextarea readonly="true" value="#{chatBean.chat}" style="width: 100%; min-height: 50%;"/>
            </div>
            <div class="chat">
                <h:inputText value="#{chatBean.msg}" style="min-width: 50%;"/>
                <h:commandButton value="Send" action="#{chatBean.send()}">
                    <f:ajax execute="@form" render="@form"/>
                </h:commandButton>
            </div>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/profile.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:p="http://primefaces.org/ui"
    template="/template.xhtml">
    <ui:define name="title">
        <title>Main page</title>
    </ui:define>
    <ui:define name="content">
        <p>You are logged as #{userProfileBean.user.login} </p>
        <h:form>
            <h:panelGrid columns="4" class="profileTable">
                <h:outputLabel value="Name:"/>
                <h:outputLabel value="#{userProfileBean.user.name}"/>
                <h:commandButton value="Change" action="#{userProfileBean.setShowInput(true)}" rendered="#{!userProfileBean.showInput}">
                    <f:ajax execute="@form" render="@form"/>
                </h:commandButton>
                <h:inputText value="#{userProfileBean.newName}" rendered="#{userProfileBean.showInput}"/>
                <h:commandButton value="Change" action="#{userProfileBean.changeName()}" rendered="#{userProfileBean.showInput}"/>
            </h:panelGrid>
        </h:form>

        <h:form>
            <h:panelGrid columns="4" class="profileTable">
                <h:outputLabel value="Gender:"/>
                <h:outputLabel value="#{userProfileBean.user.gender}"/>
                <h:commandButton value="Change" action="#{userProfileBean.setShowGenders(true)}" rendered="#{!userProfileBean.showGenders}">
                    <f:ajax execute="@form" render="@form"/>
                </h:commandButton>
                <h:selectOneListbox value="#{userProfileBean.user.gender}" rendered="#{userProfileBean.showGenders}">
                    <f:selectItems value="#{userProfileBean.genders}"/>
                </h:selectOneListbox>
                <h:commandButton value="Change" rendered="#{userProfileBean.showGenders}"/>
            </h:panelGrid>
        </h:form>
        
        <h:panelGrid columns="2" class="profileTable">
             <h:outputLabel value="Money:"/>
             <h:outputLabel value="#{userProfileBean.user.money} $"/>
             
             <h:outputLabel value="Animal collection:" />
             <h:outputLabel/>
             <h:outputLabel value="Collection is empty" rendered="#{!userProfileBean.listPopulated}"/>
             <h:dataTable value="#{userProfileBean.user.ownedAnimals}" var="animal" rendered="#{userProfileBean.listPopulated}">
                <h:column>
                    <h:graphicImage library="default" name="#{animal.imgPath}" alt="#{animal.name}+.img"/>
                </h:column>
                 <h:column>#{animal.name}</h:column>
             </h:dataTable>
        </h:panelGrid>

    </ui:define>
</ui:composition>

src/main/webapp/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">   
    <h:head>
        <ui:insert name="title">
            <title>Pet Store</title>
        </ui:insert>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <h:outputStylesheet library="default" name="/css/default-style.css"/>
        <h:outputScript library="default" name="/javascript/script.js" />
    </h:head>
    <h:body>
        <header>
            <h1>Pet Store</h1>
        </header>
        <nav>
            <ul>
                <li><a href="faces/test.xhtml">Log out</a></li>
                <li><a href="faces/animal_list.xhtml">Store</a></li>
                <li><a href="faces/chat.xhtml">Chat</a></li>
                <li><a href="faces/profile.xhtml">Profile</a></li>
                <li><a href="faces/add_animal.xhtml">Add animal</a></li>
                <li id="cash"><b>#{userProfileBean.user.money}$</b></li>
            </ul>
        </nav>
        <section>
            <ui:insert name="content"/>
        </section>
        <footer>
            <h3>Damun Modzielewski (c)</h3>
        </footer>
    </h:body>
</html>